_BASE_: ../maskformer2_R50_bs16_50ep.yaml
MODEL:
  BACKBONE:
    NAME: "AutoFocusFormer"
  AFF:
    EMBED_DIM: [96,192,384,768]
    DEPTHS: [3,4,18,2]
    NUM_HEADS: [3,6,12,24]
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    MLP_RATIO: 3.
    CLUSTER_SIZE: 8
    NBHD_SIZE: [48,48,48,48]
    LAYER_SCALE: 1e-5 # turned off if 0.0
    ALPHA: 4.0
    DS_RATE: 0.25
  WEIGHTS: "aff_small.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
SOLVER:
  IMS_PER_BATCH: 64
  BASE_LR: 0.0002
  STEPS: (81945, 88773)
  MAX_ITER: 92188 
  WARMUP_ITERS: 3
  CHECKPOINT_PERIOD: 2500
TEST:
  EVAL_PERIOD: 2500
